### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by rorolym** [heminei/vscode-pro-deployer#2]
Hi,

When i clicked upload button it gives me this error.

`[2021-10-06 18:23:56.385] [exthost] [error] Error: ENOENT: no such file or directory, open '/c:/Users/Administrator/Desktop/panel/.gitignore'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
	at c:\Users\Administrator\.vscode\extensions\heminei.pro-deployer-0.9.5\out\extension.js:134:23
	at _executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:110879)
	at _.$executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:111317)
	at i._doInvokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13543)
	at i._invokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13227)
	at i._receiveRequest (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:11889)
	at i._receiveOneMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:10567)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:8663
	at c.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at l.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15781)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30187
	at c.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at l.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15781)
	at r._receiveMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21051)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:17929
	at c.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at v.acceptChunk (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:13142)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:12490
	at Socket.w (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) pro-deployer.upload`

If i create gitignore file and add to repository , still shows error.

Thanks

**Comment by rorolym** [comment]
Found error:

Remove line 147 from extension.ts file because unused variable generates exception
let file = fs.readFileSync(Extension.getActiveWorkspaceFolderPath() + "/.gitignore");
